# tasks
---
- name: SHOW IP INTERFACES
  cisco.ios.ios_command:
    commands:
    - show clock
    - show ip ospf nei
    - show ip route | section ospf

    # - name: Display the config
    #   debug:
    #     msg: "The hostname is {{ ansible_net_hostname }} and the IOS is {{ ansible_net_version }}"
        
  register: output
- name: SHOW DEBUG
  debug: var=output.stdout_lines
